name: Health check

on:
  push:
    branches:
      - main

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Periodic health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-erik.fly.dev/'
